import Head from 'next/head';
import Navbar from '@/layout/Navbar';
import SideBar from '@/layout/Sidebar';
import Main from '@/layout/Main';
import Footer from '@/layout/Footer';
// import { useTheme } from 'next-themes';

export default function Home() {
  return (
    <>
      <Head>
        <title>Spotify Mini Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="base-root">
        <Navbar />
        <SideBar />
        <Main />
        <Footer />
      </main>
    </>
  );
}
